# Generated by Django 4.1.3 on 2023-04-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('5', 'Priority 5'), ('4', 'Priority 4'), ('3', 'Priority 3'), ('2', 'Priority 2'), ('1', 'Priority 1')], max_length=20)),
            ],
        ),
    ]
